name: Build 

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Grant execute permission for gradlew script
      run: chmod +x gradlew
      
    - name: Clean
      run: ./gradlew clean
      
    - name: Detekt
      run: ./gradlew detekt
      
    - name: Unit tests
      run: ./gradlew test

    - name: Build
      run: ./gradlew build -x detekt -x test
