name: Build

on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Official Gradle Wrapper Validation Action
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew script
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -x detekt -x test

      - name: Detekt
        run: ./gradlew detekt

      - name: Unit tests
        run: ./gradlew test

      - name: Test reporting
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/test-results/testReleaseUnitTest/**/*.xml'
          detailed_summary: true
