name: CI Konstellation library modules

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Official Gradle Wrapper Validation Action
        uses: gradle/wrapper-validation-action@v1

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew script
        run: chmod +x gradlew

      - name: Global build
        run: ./gradlew build -x detekt -x test

  unit-test-and-code-analysis:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        konstellation_modules: [
          'core',
          'charts:line',
        ]
    steps:
      - name: Detekt code analysis on ${{ matrix.konstellation_modules }}
        run: ./gradlew ":${{ matrix.konstellation_modules }}:detekt"

      - name: Unit tests on ${{ matrix.konstellation_modules }}
        run: ./gradlew ":${{ matrix.konstellation_modules }}:test"

      - name: Test reporting
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/test-results/testReleaseUnitTest/**/*.xml'
          detailed_summary: true
